---
spring:
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=year;
    username: sa
    password: null
  sql:
    init:
      mode: "embedded"
      platform: "h2"
  jpa:
    show-sql: false
    database-platform: "H2"
    generate-ddl: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:8080/auth/realms/car-services/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: car-models-service
            authorization-grant-type: authorization_code
            client-secret: eGtdvx8kd5XZ2ThQ1YlqWS5y7kuTGJwk
            scope:
              - openid
            client-authentication-method: client_secret_post
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/car-services
            user-name-attribute: preferred_username
keycloak:
  policy-enforcer-config:
    realm: "car-services"
    auth-server-url: "http://localhost:8080/auth"
    resource: "car-models-service"
    credentials:
      secret: "eGtdvx8kd5XZ2ThQ1YlqWS5y7kuTGJwk"
    enforcement-mode: "ENFORCING"
    http-method-as-scope: true
server:
  port: 8180

logging.level.org.springframework.security: "info"
#logging:
#  level:
#    root: "warn"
#    org: "info"
#    springframework:
#      security: INFO
application:
  model-sort-direction: "ASC"
  model-sort-by: name
  manufacturer-sort-direction: ASC
  manufacturer-sort-by: name
