services:
  car-models-service:
    image: foxminded/car-models-service
    build:
      context: ../car-models-service-core
      target: development
    networks:
      - car-service
    ports:
      - 8180:8180
    environment:
      - POSTGRES_HOST=cars-database
      - KEYCLOAK_HOST=keycloak
    depends_on:
      keycloak-server:
        condition: service_healthy
      cars-database:
        condition: service_healthy

  cars-database:
    networks:
      car-service:
        aliases:
          - cars-database
    image: postgres:15.0
    environment:
      - POSTGRES_USER=cars
      - POSTGRES_PASSWORD=cars
    volumes:
      - car-postgres_data:/var/lib/postgresql/data
      - car-postgres_config:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cars -d cars"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 2s
      start_interval: 2s

  keycloak-server:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    networks:
      car-service:
        aliases:
          - keycloak
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: $PWD/config/realm-config.json
        target: /opt/keycloak/data/import/realm-config.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HEALTH_ENABLED=true

    healthcheck:
      test: ["CMD-SHELL",
             'exec 3<>/dev/tcp/keycloak/8080; \
             echo -e "GET /auth/health/ready HTTP/1.1\nhost: keycloak:8080\n" >&3; \
             timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; \
             exec 3<&-; exec 3>&-; exit $ERROR']
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
      start_interval: 5s
    depends_on:
      keycloak-database:
        condition: service_healthy

  keycloak-database:
    networks:
      car-service:
        aliases:
          - keycloak-postgres
    image: postgres:15.0
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - keycloak-postgres_data:/var/lib/postgresql/data
      - keycloak-postgres_config:/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 2s
      start_interval: 2s

networks:
  car-service:

volumes:
  car-postgres_data:
  car-postgres_config:
  keycloak-postgres_data:
  keycloak-postgres_config:
