---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars
    username: cars
    password: 1234
  flyway:
    enabled: true
  jpa:
    show_sql: false
    generate-ddl: false
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/car-services/protocol/openid-connect
          audiences:
          - http://localhost:8180
          jwk-set-uri: http://localhost:8080/auth/realms/car-services/protocol/openid-connect/certs
---
#keycloak:
#  realm: car-services
#  auth-server-url: http://localhost:8090
#  resource: car-models-service
#  credentials:
#    secret: qHWnbkhwlhQ7i1qs6K6y3mJMXS2II9dc
#  policy-enforcer-config:
#    realm: car-services
#    auth-server-url: http://localhost:8090
#    resource: car-models-service
#    credentials:
#      secret: qHWnbkhwlhQ7i1qs6K6y3mJMXS2II9dc
---  
server:
  port: 8180
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
---
application:
  sort:
    category:
      by: name
      direction: ASC
    manufacturer:
      by: name
      direction: ASC
    model-name:
      by: name
      direction: ASC
    model:
      by: year
      direction: DESC      