---
spring:
  jpa:
    show_sql: false
    generate-ddl: false
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 200

category-sort-prameter: name
category-sort-direction: ASC
manufacturer-sort-parameter: name
manufacturer-sort-direction: ASC
model-sort-parameter: name
model-sort-direction: ASC
vehicle-sort-parameter: productionYear
vehicle-sort-direction: DESC
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vehicles
    username: vehicles
    password: 1234
  flyway:
    enabled: true
