---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars
    username: cars
    password: 1234
  flyway:
    enabled: true
  jpa:
    show_sql: false
    generate-ddl: false
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 200
---
server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
---
application:
  sort:
    category:
      by: name
      direction: ASC
    manufacturer:
      by: name
      direction: ASC
    model-name:
      by: name
      direction: ASC
    model:
      by: year
      direction: DESC
      