spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cars
    username: cars
    password: cars
  flyway:
    enabled: true
  jpa:
    show_sql: false
    generate-ddl: false
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 200
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:8080/auth/realms/car-services/protocol/openid-connect/certs

logging:
  level:
    root: info

keycloak:
  policy-enforcer-config:
    realm: car-services
    auth-server-url: http://${KEYCLOAK_HOST:localhost}:8080/auth
    resource: car-models-service
    credentials:
      secret: eGtdvx8kd5XZ2ThQ1YlqWS5y7kuTGJwk
    enforcement-mode: ENFORCING
    http-method-as-scope: true
  
server:
  port: 8180
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
    
springdoc:
  api-docs:
    path: ${springdoc.path}
  

application:
  sort:
    category:
      by: name
      direction: ASC
    manufacturer:
      by: name
      direction: ASC
    model-name:
      by: name
      direction: ASC
    model:
      by: year
      direction: DESC      